#!/usr/bin/env python3
"""Regenerate assets/ASSETS.md (inventory + licenses + animation clip names).

    python tools/import_assets.py
    godot --headless --path . --import
    godot --headless --path . -s tools/dump_clips.gd     # writes assets/animation_clips.json
    python tools/gen_assets_md.py
"""
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ASSETS = REPO / "assets"
MANIFEST = REPO / "tools" / "asset_manifest.json"
SKIP_SUFFIX = {".import", ".uid", ".md", ".json"}
SKIP_NAMES = {".gitkeep"}


def license_info(path: Path) -> tuple[str, str]:
    lines = [l.strip() for l in path.read_text(encoding="utf-8", errors="replace").splitlines() if l.strip()]
    title = lines[0]
    m = re.search(r"License:\s*\(([^)]*)\)", path.read_text(encoding="utf-8", errors="replace"))
    return title, (m.group(1) if m else "see LICENSE.txt")


def main() -> None:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    packs: dict[str, dict] = {}
    for e in manifest:
        p = packs.setdefault(e["pack"], {"dests": [], "title": e["pack"], "license": "unknown", "family": e["dest"].split("/")[0]})
        p["dests"].append(e["dest"])
        if e.get("license"):
            p["title"], p["license"] = license_info(ASSETS / e["dest"] / "LICENSE.txt")

    dest_to_pack = {d: name for name, p in packs.items() for d in p["dests"]}
    by_pack: dict[str, list[str]] = {name: [] for name in packs}
    for f in sorted(ASSETS.rglob("*")):
        if not f.is_file() or f.suffix in SKIP_SUFFIX or f.name in SKIP_NAMES:
            continue
        rel = f.relative_to(ASSETS).as_posix()
        owner = max((d for d in dest_to_pack if rel.startswith(d + "/")), key=len, default=None)
        if owner is None:
            raise SystemExit(f"{rel} is not covered by tools/asset_manifest.json")
        by_pack[dest_to_pack[owner]].append(rel)

    out = ["# Asset inventory", "",
           "Generated by `tools/gen_assets_md.py`; do not edit by hand. Files are copied from `D:\ASSETS\KayKit` "
           "by `tools/import_assets.py` (see `tools/asset_manifest.json`). Each pack's license text sits in its folder as `LICENSE.txt`.", ""]
    for family, heading in (("kaykit", "KayKit (Kay Lousberg)"), ("kenney", "Kenney")):
        out += [f"## {heading}", ""]
        for name, p in packs.items():
            if p["family"] != family:
                continue
            files = by_pack[name]
            out += [f"### {p['title']}", "", f"- Source folder: `{name}`", f"- License: {p['license']}", f"- Files: {len(files)}", "",
                    "| File |", "| --- |"] + [f"| `{r}` |" for r in files] + [""]

    clips_path = ASSETS / "animation_clips.json"
    if clips_path.exists():
        clips = json.loads(clips_path.read_text(encoding="utf-8"))
        out += ["## Animation clip names", "",
                "Imported from `kaykit/animations/rig_*`. Adventurer and skeleton characters use `Rig_Medium`. "
                "Clips live in the unnamed library of each file's `AnimationPlayer`.", ""]
        for rig, files in clips.items():
            out += [f"### {rig}", ""]
            for fname, names in sorted(files.items()):
                out += [f"- **{fname}** ({len(names)}): " + ", ".join(f"`{n}`" for n in names)]
            out += [""]
    (ASSETS / "ASSETS.md").write_text("\n".join(out), encoding="utf-8", newline="\n")
    print("wrote", ASSETS / "ASSETS.md")


if __name__ == "__main__":
    main()
